ALTER TABLE TB_SUGGESTION_TEMPLATE ADD COLUMN book_template_id BIGINT;

ALTER TABLE TB_SUGGESTION_TEMPLATE ADD CONSTRAINT fk_st_to_book_template FOREIGN KEY (book_template_id) REFERENCES TB_BOOK_TEMPLATE (book_template_id) ON DELETE CASCADE;

CREATE INDEX idx_TB_SUGGESTION_TEMPLATE_bt_id ON TB_SUGGESTION_TEMPLATE(book_template_id);