ALTER TABLE TB_BOOK_TEMPLATE ADD COLUMN status varchar(100) NOT NULL DEFAULT 'VERIFIED';

ALTER TABLE TB_BOOK_TEMPLATE ADD CONSTRAINT chk_TB_BOOK_TEMPLATE_status CHECK (status in ('IN_ANALYZE', 'INACTIVE', 'VERIFIED', 'DECLINE'));

ALTER TABLE TB_SUGGESTION_TEMPLATE DROP CONSTRAINT chk_TB_SUGGESTION_TEMPLATE_status;

ALTER TABLE TB_SUGGESTION_TEMPLATE ADD CONSTRAINT chk_TB_SUGGESTION_TEMPLATE_status CHECK (status in ('IN_ANALYZE', 'INACTIVE', 'VERIFIED', 'DECLINE'));