ALTER TABLE TB_BOOK ADD COLUMN user_id BIGINT NOT NULL;

ALTER TABLE TB_BOOK ADD CONSTRAINT fk_book_to_user FOREIGN KEY (user_id) REFERENCES TB_USER(user_id) ON DELETE RESTRICT;

CREATE INDEX idx_TB_BOOK_user_id ON TB_BOOK(user_id);